services:
  app:
    build:
      context: .
    container_name: app
    restart: on-failure
    env_file:
      - .env

  test:
    build:
      context: .
    container_name: test
    restart: no
    command: ./vendor/bin/phpunit --configuration phpunit.xml
